(() => {
  'use strict';
  const FORMAT = 'evolucao-multidisciplinar-upa24';
  const EXTENSION = '.upa24';
  const ROWS_PER_PAGE = 20;
  const TOTAL_ROWS = 42;
  const state = { handle: null, fileName: '', dirty: false, busy: false, source: {} };
  const $ = (s) => document.querySelector(s);
  const $$ = (s) => [...document.querySelectorAll(s)];
  const esc = (v='') => String(v).replace(/[&<>"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
  const localDate = () => { const d=new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; };
  const valueAt = (o, paths, fallback='') => { for(const p of paths){ const v=p.split('.').reduce((a,k)=>a?.[k],o); if(v!==undefined&&v!==null)return v; } return fallback; };
  function header(first){
    if(!first) return '';
    return `<table class="header"><tr><td class="logo" rowspan="3"><img src="../logo-sbc.jpg" alt="Prefeitura de São Bernardo do Campo"></td><td class="city">MUNICÍPIO DE SÃO BERNARDO DO CAMPO</td></tr><tr><td class="secretary">Secretaria da Saúde</td></tr><tr><td class="unit">Unidade de Pronto Atendimento<br><span id="unit-label">Riacho Grande</span></td></tr></table>
    <table class="patient"><tr><td colspan="2">NOME: <input id="nome" autocomplete="off"></td></tr><tr><td class="split">SALA: <input id="sala" autocomplete="off"></td><td class="small">LEITO: <input id="leito" autocomplete="off"></td></tr><tr><td>HD: <input id="diagnosticos" autocomplete="off"></td><td>IDADE: <input id="idade" autocomplete="off"></td></tr></table>`;
  }
  function rows(start,count){return Array.from({length:count},(_,i)=>{const n=start+i;return `<tr data-row="${n}"><td class="date-time"><label class="visually-hidden" for="data-${n}">Data</label><input id="data-${n}" class="row-date" type="date"><label class="visually-hidden" for="hora-${n}">Hora</label><input id="hora-${n}" class="row-time" type="time"></td><td class="entry"><textarea aria-label="Evolução ${n+1}" spellcheck="true"></textarea></td></tr>`}).join('')}
  function page(number,start,count){return `<section class="sheet ${number===2?'page-two':''}">${header(number===1)}<table class="evolution"><thead><tr><th class="datetime">DATA/HORA</th><th>EVOLUÇÃO MULTIDISCIPLINAR</th></tr></thead><tbody>${rows(start,count)}${number===2?'<tr><td class="footer" colspan="2">Rua Marcílio Conrado, 333 - RIACHO GRANDE - CNPJ 46.523.239/0001-47</td></tr>':''}</tbody></table></section>`}
  $('#pages').innerHTML=page(1,0,ROWS_PER_PAGE)+page(2,ROWS_PER_PAGE,TOTAL_ROWS-ROWS_PER_PAGE);
  function setStatus(message){const e=$('#document-status');e.textContent=(message||state.fileName||'Novo documento')+(state.dirty?' — alterações não salvas':'');e.classList.toggle('unsaved',state.dirty);document.title=`Evolução Multidisciplinar${state.dirty?' *':''}`}
  function markDirty(){if(!state.busy){state.dirty=true;setStatus()}}
  function normalizeUnit(v){return String(v||'UPA RIACHO GRANDE').replace(/^UPA\s+/i,'').trim()||'Riacho Grande'}
  function collect(){const base=structuredClone(state.source||{});base.formatoOriginal=base.formato||null;base.formato=FORMAT;base.versaoEvolucao=1;base.aplicativoEvolucao={nome:'Evolução Multidisciplinar',versao:'1.0.0'};base.ultimaAlteracao=new Date().toISOString();base.unidade=base.unidade||`UPA ${$('#unit-label').textContent}`;base.paciente={...(base.paciente||{}),nome:$('#nome').value,idade:$('#idade').value||base.paciente?.idade||null};base.atendimento={...(base.atendimento||{}),diagnosticos:$('#diagnosticos').value,sala:$('#sala').value,leito:$('#leito').value};base.evolucao=$$('tr[data-row]').map((r,i)=>({numero:i+1,data:r.querySelector('.row-date').value,hora:r.querySelector('.row-time').value,texto:r.querySelector('textarea').value}));return base}
  function apply(data){state.source=structuredClone(data);$('#nome').value=valueAt(data,['paciente.nome','nome']);$('#sala').value=valueAt(data,['atendimento.sala','sala']);$('#leito').value=valueAt(data,['atendimento.leito','leito']);$('#diagnosticos').value=valueAt(data,['atendimento.diagnosticos','atendimento.diagnostico','diagnosticos']);$('#idade').value=valueAt(data,['paciente.idade','idade']);$('#unit-label').textContent=normalizeUnit(valueAt(data,['unidade.nome','unidade','atendimento.unidade']));const evol=Array.isArray(data.evolucao)?data.evolucao:Array.isArray(data.evolucoes)?data.evolucoes:[];$$('tr[data-row]').forEach((r,i)=>{const e=evol.find(x=>Number(x.numero)===i+1)||evol[i]||{};r.querySelector('.row-date').value=String(e.data||'').slice(0,10);r.querySelector('.row-time').value=e.hora||e.horario||'';r.querySelector('textarea').value=e.texto||e.evolucao||''});state.dirty=false;setStatus()}
  function reset(){if(state.dirty&&!confirm('Descartar as alterações não salvas?'))return;state.handle=null;state.fileName='';state.source={};$$('input:not([type=file]),textarea').forEach(e=>e.value='');$('#unit-label').textContent='Riacho Grande';state.dirty=false;setStatus()}
  async function readFile(file,handle=null){try{const data=JSON.parse(await file.text());if(!data||typeof data!=='object'||Array.isArray(data))throw new Error('Conteúdo inválido');state.handle=handle;state.fileName=file.name;apply(data);setStatus(`Aberto: ${file.name}`)}catch(e){alert(`Não foi possível abrir o arquivo.\n\n${e.message}`)}}
  const pickerTypes=()=>[{description:'Arquivo UPA24',accept:{'application/json':[EXTENSION]}}];
  async function openFile(){if(state.dirty&&!confirm('Descartar as alterações não salvas?'))return;if('showOpenFilePicker'in window){try{const [h]=await showOpenFilePicker({types:pickerTypes(),multiple:false});await readFile(await h.getFile(),h)}catch(e){if(e.name!=='AbortError')alert(e.message)}}else $('#file-input').click()}
  function suggested(){const patient=$('#nome').value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/gi,'-').replace(/^-|-$/g,'').toLowerCase()||'paciente';return `evolucao-${patient}-${localDate()}${EXTENSION}`}
  function download(data,name){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)+'\n'],{type:'application/json'}));a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
  async function write(handle,data){const permission=await handle.queryPermission?.({mode:'readwrite'});if(permission!=='granted'&&await handle.requestPermission?.({mode:'readwrite'})!=='granted')throw new Error('Permissão de gravação não concedida');const w=await handle.createWritable();await w.write(JSON.stringify(data,null,2)+'\n');await w.close()}
  async function save(as=false){const data=collect();try{if('showSaveFilePicker'in window){let h=state.handle;if(as||!h)h=await showSaveFilePicker({suggestedName:suggested(),types:pickerTypes()});await write(h,data);state.handle=h;state.fileName=h.name}else{download(data,suggested());state.handle=null;state.fileName=suggested()}state.source=structuredClone(data);state.dirty=false;setStatus(`Salvo: ${state.fileName}`)}catch(e){if(e.name!=='AbortError')alert(`Não foi possível salvar.\n\n${e.message}`)}}
  document.addEventListener('input',markDirty);$('#open-button').onclick=openFile;$('#clear-button').onclick=reset;$('#save-button').onclick=()=>save(false);$('#save-as-button').onclick=()=>save(true);$('#print-button').onclick=()=>window.print();$('#file-input').onchange=e=>{const f=e.target.files?.[0];if(f)readFile(f);e.target.value=''};window.addEventListener('beforeunload',e=>{if(state.dirty){e.preventDefault();e.returnValue=''}});if('launchQueue'in window)launchQueue.setConsumer(async params=>{const h=params.files?.[0];if(h)await readFile(await h.getFile(),h)});if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(console.error);
})();
